In [3]:
import duckdb

conn = duckdb.connect("procurement.duckdb")

In [14]:
data = conn.execute("""
    SELECT release_id,
            ocid,
            release_date,
            raw_json
    FROM raw_releases
""").fetchone()

In [15]:
print(data)

('092770-2026', 'ocds-h6vhtk-06759b', datetime.datetime(2026, 10, 1, 11, 46, 44, tzinfo=<DstTzInfo 'Europe/London' BST+1:00:00 DST>), '{"id": "092770-2026", "tag": ["award", "contract"], "date": "2026-10-01T11:46:44+01:00", "initiationType": "tender", "ocid": "ocds-h6vhtk-06759b", "parties": [{"name": "Leeds Teaching Hospitals NHS Trust", "id": "GB-PPON-PNQG-8433-QXBP", "identifier": {"scheme": "GB-PPON", "id": "PNQG-8433-QXBP"}, "address": {"streetAddress": "Great George Street", "locality": "Leeds", "postalCode": "LS1 3EX", "country": "GB", "countryName": "United Kingdom", "region": "UKE42"}, "contactPoint": {"name": "North East & Yorkshire NHS Pharmaceutical Purchasing Consortium", "email": "leedsth-tr.neyregionalcontracting@nhs.net"}, "roles": ["buyer"], "details": {"url": "https://www.leedsth.nhs.uk", "classifications": [{"scheme": "UK_CA_TYPE", "id": "publicAuthorityCentralGovernment", "description": "Public authority - central government"}]}}, {"name": "Alliance Healthcare", "id": "GB-PPON-PBHQ-8556-RPBN", "identifier": {"scheme": "GB-PPON", "id": "PBHQ-8556-RPBN"}, "address": {"streetAddress": "43 Cox Lane", "locality": "Chessington, Surrey", "postalCode": "KT9 1SN", "country": "GB", "countryName": "United Kingdom", "region": "UKI63"}, "contactPoint": {"email": "alliancehealthcarebo@alliance-healthcare.co.uk"}, "roles": ["supplier"], "details": {"scale": "large", "vcse": false, "publicServiceMissionOrganization": false, "shelteredWorkshop": false}}, {"name": "AAH Pharmaceuticals Limited", "id": "GB-PPON-PLCQ-5553-XNTM", "identifier": {"scheme": "GB-PPON", "id": "PLCQ-5553-XNTM"}, "address": {"streetAddress": "The Woods, Haywood Road", "locality": "Warwick", "postalCode": "CV34 5AH", "country": "GB", "countryName": "United Kingdom", "region": "UKG13"}, "contactPoint": {"email": "tenders@aah.co.uk"}, "roles": ["supplier"], "details": {"scale": "large", "vcse": false, "publicServiceMissionOrganization": false, "shelteredWorkshop": false}}, {"name": "Phoenix Healthcare", "id": "GB-PPON-PHTH-2722-DWLT", "identifier": {"scheme": "GB-PPON", "id": "PHTH-2722-DWLT"}, "address": {"streetAddress": "Whitehouse Industrial Estate, Rivington Road", "locality": "Runcorn", "postalCode": "WA7 3DJ", "country": "GB", "countryName": "United Kingdom", "region": "UKD71"}, "contactPoint": {"email": "shaywood@phoenixmedical.co.uk"}, "roles": ["supplier"], "details": {"scale": "large", "vcse": false, "publicServiceMissionOrganization": false, "shelteredWorkshop": false}}, {"name": "Mawdsley-Brooks & Co Ltd", "id": "GB-PPON-PDHW-3339-CRZN", "identifier": {"scheme": "GB-PPON", "id": "PDHW-3339-CRZN"}, "address": {"streetAddress": "Number Three, South Langworthy Road, PO BOX 18", "locality": "Salford", "postalCode": "M50 2PW", "country": "GB", "countryName": "United Kingdom", "region": "UKD34"}, "contactPoint": {"email": "kelly.jacques@mawdsleys.co.uk"}, "roles": ["supplier"], "details": {"scale": "large", "vcse": false, "publicServiceMissionOrganization": false, "shelteredWorkshop": false}}], "buyer": {"id": "GB-PPON-PNQG-8433-QXBP", "name": "Leeds Teaching Hospitals NHS Trust"}, "tender": {"id": "C425493", "legalBasis": {"id": "2023/54", "scheme": "UKPGA", "uri": "https://www.legislation.gov.uk/ukpga/2023/54/contents"}, "title": "NEYPPC Licensed Medicines Provision of Pharmaceutical Wholesale Services 26", "description": "Framework agreement for Licensed Wholesaler Services contract for the delivery of medicines to Trusts within the North East and North Cumbria, Yorkshire and The Humber and North West Regions.\\nThis was procured via an Open Procedure to award a Closed Framework.", "status": "complete", "procurementMethod": "open", "procurementMethodDetails": "Open procedure", "participationFees": [{"type": ["win"], "relativeValue": {"proportion": 0.01, "monetaryValue": "award"}, "description": "1% ABI charge for non contracted goods liable for discount", "id": "ocds-h6vhtk-06759b"}], "techniques": {"hasFrameworkAgreement": true, "frameworkAgreement": {"method": "withoutReopeningCompetition", "type": "open", "buyerLocationRestrictions": [{"gazetteer": {"scheme": "GB-ITL", "identifiers": ["UKC"]}}, {"gazetteer": {"scheme": "GB-ITL", "identifiers": ["UKD"]}}, {"gazetteer": {"scheme": "GB-ITL", "identifiers": ["UKE"]}}], "buyerCategories": "This Framework Agreement will include and be for the benefit of publicly funded (both wholly and partially funded) entities in the United Kingdom, including Northern Ireland, Scotland, Wales and England. This will include but is not limited to:  Acute; (including their third-party providers); Ambulance; Mental Health; Clinical Commissioning Groups; Health and Care Trusts; Area Teams; Local Authorities and Special Health Authorities; HSC in Northern Ireland; and NHS Wales, including any successor or emerging organisations, which will include but is not limited to the emerging landscape of combined health and social care commissioners and providers.", "description": "Framework agreement for Licensed Wholesaler Services contract for the delivery of medicines to Trusts within the North East and North Cumbria, Yorkshire and The Humber and North West Regions."}}, "lots": [{"id": "1", "status": "complete"}], "documents": [{"id": "conflictOfInterest", "documentType": "conflictOfInterest", "description": "Not published"}]}, "awards": [{"id": "1", "status": "active", "mainProcurementCategory": "goods", "suppliers": [{"id": "GB-PPON-PBHQ-8556-RPBN", "name": "Alliance Healthcare"}, {"id": "GB-PPON-PLCQ-5553-XNTM", "name": "AAH Pharmaceuticals Limited"}, {"id": "GB-PPON-PHTH-2722-DWLT", "name": "Phoenix Healthcare"}, {"id": "GB-PPON-PDHW-3339-CRZN", "name": "Mawdsley-Brooks & Co Ltd"}], "items": [{"id": "1", "additionalClassifications": [{"scheme": "CPV", "id": "33600000", "description": "Pharmaceutical products"}], "deliveryAddresses": [{"region": "UKC", "country": "GB", "countryName": "United Kingdom"}, {"region": "UKD", "country": "GB", "countryName": "United Kingdom"}, {"region": "UKE", "country": "GB", "countryName": "United Kingdom"}], "relatedLot": "1"}], "relatedLots": ["1"]}], "contracts": [{"id": "1", "awardID": "1", "title": "NEYPPC Licensed Medicines Provision of Pharmaceutical Wholesale Services 26", "status": "active", "period": {"startDate": "2026-10-01T00:00:00+01:00", "endDate": "2029-09-30T23:59:59+01:00", "maxExtentDate": "2030-09-30T23:59:59+01:00"}, "hasRenewal": true, "renewal": {"description": "1 year optional extension"}, "value": {"amountGross": 2448000000.0, "amount": 2400000000.0, "currency": "GBP"}, "aboveThreshold": true, "dateSigned": "2026-09-17T00:00:00+01:00", "documents": [{"id": "A-23339", "documentType": "contractSigned", "description": "NHS T&Cs Framework Agreement for the Supply of Goods and the Provision of Services Signed Contract", "url": "https://www.find-tender.service.gov.uk/Notice/Attachment/A-23339", "format": "application/pdf"}, {"id": "A-23351", "documentType": "contractSigned", "description": "NHS T&Cs Framework Agreement for the Supply of Goods and the Provision of Services Signed Contract", "url": "https://www.find-tender.service.gov.uk/Notice/Attachment/A-23351", "format": "application/pdf"}, {"id": "A-23341", "documentType": "contractSigned", "description": "NHS T&Cs Framework Agreement for the Supply of Goods and the Provision of Services Signed Contract", "url": "https://www.find-tender.service.gov.uk/Notice/Attachment/A-23341", "format": "application/pdf"}, {"id": "A-23342", "documentType": "contractSigned", "description": "NHS T&Cs Framework Agreement for the Supply of Goods and the Provision of Services Signed Contract", "url": "https://www.find-tender.service.gov.uk/Notice/Attachment/A-23342", "format": "application/pdf"}, {"id": "092770-2026", "documentType": "contractNotice", "noticeType": "UK7", "description": "Contract details notice on Find a Tender", "url": "https://www.find-tender.service.gov.uk/Notice/092770-2026", "datePublished": "2026-10-01T11:46:44+01:00", "format": "text/html"}], "agreedMetrics": [{"id": "0813", "title": "Total Sales", "description": "The total value of goods (exc. VAT) supplied against all pharmacy accounts within the reporting period.", "observations": [{"period": {"durationInMonths": 1}, "id": "frequency"}]}, {"id": "0814", "title": "Order lines not on time and in full vs number of order lines.", "description": "Number of order lines not on time and in full as a percentage of number of order lines.", "observations": [{"period": {"durationInMonths": 1}, "id": "frequency"}]}, {"id": "0815", "title": "Value of debt (30 + days) vs total sales", "description": "Value of  debt remaining unpaid which is greater than 30 days from the invoice date as a percentage of total sales.", "observations": [{"period": {"durationInMonths": 1}, "id": "frequency"}]}]}], "language": "en"}')

In [16]:
data = conn.execute("""
    SELECT
        release_id,
        raw_json ->> '$.initiationType' AS initiation_type
    FROM raw_releases
    LIMIT 5
""").df()

data

    release_id initiation_type
0  092770-2026          tender
1  092769-2026          tender
2  092768-2026          tender
3  092767-2026          tender
4  092766-2026          tender

In [24]:
data = conn.execute("""
    SELECT
        release_id,
        raw_json ->> '$.buyer.name' AS buyer_name,
        raw_json ->> '$.tender.title' as tender_title,
        raw_json ->> '$.tender.status' as tender_status,
        raw_json ->> '$.tender.procurementMethod' as procurement_method,
        cast(raw_json ->> '$.tender.value.amount' as DECIMAL(19,2)) as tender_value,
        raw_json ->> '$.tender.value.currency' as currency
    FROM raw_releases
    LIMIT 5
""").df()

data

,release_id,buyer_name,tender_title,tender_status,procurement_method,tender_value,currency
0,092770-2026,Leeds Teaching Hospitals NHS Trust,NEYPPC Licensed Medicines Provision of Pharmac...,complete,open,NaN,None
1,092769-2026,Post Office Limited,Post Office Branch - Inchture,active,open,NaN,GBP
2,092768-2026,London Borough of Bromley,"Water Quality Monitoring, Citizen Science & Co...",complete,limited,NaN,None
3,092767-2026,High Speed Two (HS2) Limited,HS2 Residual Works Framework,planned,None,2.200000e+09,GBP
4,092766-2026,None,External Consultancy Support in relation to Ad...,None,None,NaN,None

In [30]:
data = conn.execute("""
    SELECT
        ocid,
        count(release_id)
    FROM raw_releases
    group by ocid
    having count(release_id) > 1
    order by count(release_id) desc
""").df()

data

                  ocid  count(release_id)
0   ocds-h6vhtk-029897                  6
1   ocds-h6vhtk-06b80d                  3
2   ocds-h6vhtk-077fa9                  3
3   ocds-h6vhtk-077e91                  3
4   ocds-h6vhtk-077eb6                  3
..                 ...                ...
60  ocds-h6vhtk-077e7e                  2
61  ocds-h6vhtk-0777fc                  2
62  ocds-h6vhtk-077dac                  2
63  ocds-h6vhtk-0695b1                  2
64  ocds-h6vhtk-068a76                  2

[65 rows x 2 columns]

In [35]:
data = conn.execute("""
    SELECT
        release_id,
        ocid,
        release_date,
        tags,
        raw_json ->> '$.buyer.name' AS buyer_name,
        raw_json ->> '$.tender.title' as tender_title,
        raw_json ->> '$.tender.status' as tender_status,
        raw_json ->> '$.tender.procurementMethod' as procurement_method,
        cast(raw_json ->> '$.tender.value.amount' as DECIMAL(19,2)) as tender_value,
        raw_json ->> '$.tender.value.currency' as currency
    FROM raw_releases
    where ocid = 'ocds-h6vhtk-029897'
    order by release_date
""").df()

data

,release_id,ocid,release_date,tags,buyer_name,tender_title,tender_status,procurement_method,tender_value,currency
0,092702-2026,ocds-h6vhtk-029897,2026-10-01 10:37:42+01:00,"[""award"", ""contract""]",London Borough of Merton,Taxi Vehicles with Passenger Assistant,complete,open,NaN,None
1,093155-2026,ocds-h6vhtk-029897,2026-10-02 10:03:43+01:00,"[""award"", ""contract""]",London Borough of Merton,Taxi Vehicles with Passenger Assistant,complete,open,NaN,None
2,093156-2026,ocds-h6vhtk-029897,2026-10-02 10:05:43+01:00,"[""award"", ""contract""]",London Borough of Merton,Taxi Vehicles with Passenger Assistant,complete,open,NaN,None
3,093159-2026,ocds-h6vhtk-029897,2026-10-02 10:07:43+01:00,"[""award"", ""contract""]",London Borough of Merton,Taxi Vehicles with Passenger Assistant,complete,open,NaN,None
4,093215-2026,ocds-h6vhtk-029897,2026-10-02 11:13:39+01:00,"[""award"", ""contract""]",London Borough of Merton,Taxi Vehicles,complete,open,NaN,None
5,093251-2026,ocds-h6vhtk-029897,2026-10-02 11:41:45+01:00,"[""award"", ""contract""]",London Borough of Merton,Taxi Vehicles with Passenger Assistant,complete,open,NaN,None

In [36]:
dbt --version

NameError: name 'dbt' is not defined

In [38]:
import duckdb

conn = duckdb.connect("procurement.duckdb")

In [39]:
data = conn.execute("""
    SELECT
        *
    FROM stg_releases
    LIMIT 5
""").df()

data

,release_id,ocid,release_date,tags,buyer_name,tender_title,tender_status,procurement_method,tender_value,currency
0,092770-2026,ocds-h6vhtk-06759b,2026-10-01 11:46:44+01:00,"[""award"", ""contract""]",Leeds Teaching Hospitals NHS Trust,NEYPPC Licensed Medicines Provision of Pharmac...,complete,open,NaN,None
1,092769-2026,ocds-h6vhtk-077e7b,2026-10-01 11:46:41+01:00,"[""tender""]",Post Office Limited,Post Office Branch - Inchture,active,open,NaN,GBP
2,092768-2026,ocds-h6vhtk-077e7a,2026-10-01 11:46:10+01:00,"[""award"", ""contract""]",London Borough of Bromley,"Water Quality Monitoring, Citizen Science & Co...",complete,limited,NaN,None
3,092767-2026,ocds-h6vhtk-06ecf6,2026-10-01 11:45:29+01:00,"[""planningUpdate""]",High Speed Two (HS2) Limited,HS2 Residual Works Framework,planned,None,2.200000e+09,GBP
4,092766-2026,ocds-h6vhtk-064e67,2026-10-01 11:44:37+01:00,"[""contractTermination""]",None,External Consultancy Support in relation to Ad...,None,None,NaN,None

In [40]:
conn.close()

In [41]:
import duckdb

conn = duckdb.connect("procurement.duckdb")

In [45]:
data = conn.execute("""
    SELECT
    release_id,
    json_array_length(raw_json, '$.awards') AS award_count
    FROM raw_releases
    LIMIT 10
""").df()

data

    release_id  award_count
0  092770-2026            1
1  092769-2026         <NA>
2  092768-2026            1
3  092767-2026         <NA>
4  092766-2026         <NA>
5  092765-2026            1
6  092764-2026            1
7  092763-2026         <NA>
8  092762-2026            1
9  092761-2026         <NA>

In [47]:
data = conn.execute("""
    SELECT
    max(json_array_length(raw_json, '$.awards')) AS max_award_count
    FROM raw_releases
""").df()

data

   max_award_count
0              127

In [49]:
data = conn.execute("""
    SELECT
    release_id,
    ocid,
    release_date,
    json_array_length(raw_json, '$.awards') AS award_count
    FROM raw_releases
    where award_count = 127
""").df()

data

    release_id                ocid              release_date  award_count
0  092612-2026  ocds-h6vhtk-0510f8 2026-09-30 23:30:39+01:00          127

In [60]:
data = conn.execute("""
    SELECT
    
    raw_json -> '$.awards' AS awards
    FROM raw_releases
    where release_id = '092612-2026'
""").fetchone()[0]

print(data)

[{"id":"1","amendments":[{"id":"092612-2026"}]},{"id":"2","amendments":[{"id":"092612-2026"}]},{"id":"3","amendments":[{"id":"092612-2026"}]},{"id":"4","amendments":[{"id":"092612-2026"}]},{"id":"5","amendments":[{"id":"092612-2026"}]},{"id":"6","amendments":[{"id":"092612-2026"}]},{"id":"7","amendments":[{"id":"092612-2026"}]},{"id":"8","amendments":[{"id":"092612-2026"}]},{"id":"9","amendments":[{"id":"092612-2026"}]},{"id":"10","amendments":[{"id":"092612-2026"}]},{"id":"11","amendments":[{"id":"092612-2026"}]},{"id":"12","amendments":[{"id":"092612-2026"}]},{"id":"13","amendments":[{"id":"092612-2026"}]},{"id":"14","amendments":[{"id":"092612-2026"}]},{"id":"15","amendments":[{"id":"092612-2026"}]},{"id":"16","amendments":[{"id":"092612-2026"}]},{"id":"17","amendments":[{"id":"092612-2026"}]},{"id":"18","amendments":[{"id":"092612-2026"}]},{"id":"19","amendments":[{"id":"092612-2026"}]},{"id":"20","amendments":[{"id":"092612-2026"}]},{"id":"21","amendments":[{"id":"092612-2026"}]},{"id":"22","amendments":[{"id":"092612-2026"}]},{"id":"23","amendments":[{"id":"092612-2026"}]},{"id":"24","amendments":[{"id":"092612-2026"}]},{"id":"25","amendments":[{"id":"092612-2026"}]},{"id":"26","amendments":[{"id":"092612-2026"}]},{"id":"27","amendments":[{"id":"092612-2026"}]},{"id":"28","amendments":[{"id":"092612-2026"}]},{"id":"29","amendments":[{"id":"092612-2026"}]},{"id":"30","amendments":[{"id":"092612-2026"}]},{"id":"31","amendments":[{"id":"092612-2026"}]},{"id":"32","amendments":[{"id":"092612-2026"}]},{"id":"33","amendments":[{"id":"092612-2026"}]},{"id":"34","amendments":[{"id":"092612-2026"}]},{"id":"35","amendments":[{"id":"092612-2026"}]},{"id":"36","amendments":[{"id":"092612-2026"}]},{"id":"37","amendments":[{"id":"092612-2026"}]},{"id":"38","amendments":[{"id":"092612-2026"}]},{"id":"39","amendments":[{"id":"092612-2026"}]},{"id":"40","amendments":[{"id":"092612-2026"}]},{"id":"41","amendments":[{"id":"092612-2026"}]},{"id":"42","amendments":[{"id":"092612-2026"}]},{"id":"43","amendments":[{"id":"092612-2026"}]},{"id":"44","amendments":[{"id":"092612-2026"}]},{"id":"45","amendments":[{"id":"092612-2026"}]},{"id":"46","amendments":[{"id":"092612-2026"}]},{"id":"47","amendments":[{"id":"092612-2026"}]},{"id":"48","amendments":[{"id":"092612-2026"}]},{"id":"49","amendments":[{"id":"092612-2026"}]},{"id":"50","amendments":[{"id":"092612-2026"}]},{"id":"51","amendments":[{"id":"092612-2026"}]},{"id":"52","amendments":[{"id":"092612-2026"}]},{"id":"53","amendments":[{"id":"092612-2026"}]},{"id":"54","amendments":[{"id":"092612-2026"}]},{"id":"55","amendments":[{"id":"092612-2026"}]},{"id":"56","amendments":[{"id":"092612-2026"}]},{"id":"57","amendments":[{"id":"092612-2026"}]},{"id":"58","amendments":[{"id":"092612-2026"}]},{"id":"59","amendments":[{"id":"092612-2026"}]},{"id":"60","amendments":[{"id":"092612-2026"}]},{"id":"61","amendments":[{"id":"092612-2026"}]},{"id":"62","amendments":[{"id":"092612-2026"}]},{"id":"63","amendments":[{"id":"092612-2026"}]},{"id":"64","amendments":[{"id":"092612-2026"}]},{"id":"65","amendments":[{"id":"092612-2026"}]},{"id":"66","amendments":[{"id":"092612-2026"}]},{"id":"67","amendments":[{"id":"092612-2026"}]},{"id":"68","amendments":[{"id":"092612-2026"}]},{"id":"69","amendments":[{"id":"092612-2026"}]},{"id":"70","amendments":[{"id":"092612-2026"}]},{"id":"71","amendments":[{"id":"092612-2026"}]},{"id":"72","amendments":[{"id":"092612-2026"}]},{"id":"73","amendments":[{"id":"092612-2026"}]},{"id":"74","amendments":[{"id":"092612-2026"}]},{"id":"75","amendments":[{"id":"092612-2026"}]},{"id":"76","amendments":[{"id":"092612-2026"}]},{"id":"77","amendments":[{"id":"092612-2026"}]},{"id":"78","amendments":[{"id":"092612-2026"}]},{"id":"79","amendments":[{"id":"092612-2026"}]},{"id":"80","amendments":[{"id":"092612-2026"}]},{"id":"81","amendments":[{"id":"092612-2026"}]},{"id":"82","amendments":[{"id":"092612-2026"}]},{"id":"83","amendments":[{"id":"092612-2026"}]},{"id":"84","amendments":[{"id":"092612-2026"}]},{"id":"85","amendments":[{"id":"092612-2026"}]},{"id":"86","amendments":[{"id":"092612-2026"}]},{"id":"87","amendments":[{"id":"092612-2026"}]},{"id":"88","amendments":[{"id":"092612-2026"}]},{"id":"89","amendments":[{"id":"092612-2026"}]},{"id":"90","amendments":[{"id":"092612-2026"}]},{"id":"91","amendments":[{"id":"092612-2026"}]},{"id":"92","amendments":[{"id":"092612-2026"}]},{"id":"93","amendments":[{"id":"092612-2026"}]},{"id":"94","amendments":[{"id":"092612-2026"}]},{"id":"95","amendments":[{"id":"092612-2026"}]},{"id":"96","amendments":[{"id":"092612-2026"}]},{"id":"97","amendments":[{"id":"092612-2026"}]},{"id":"98","amendments":[{"id":"092612-2026"}]},{"id":"99","amendments":[{"id":"092612-2026"}]},{"id":"100","amendments":[{"id":"092612-2026"}]},{"id":"101","amendments":[{"id":"092612-2026"}]},{"id":"102","amendments":[{"id":"092612-2026"}]},{"id":"103","amendments":[{"id":"092612-2026"}]},{"id":"104","amendments":[{"id":"092612-2026"}]},{"id":"105","amendments":[{"id":"092612-2026"}]},{"id":"106","amendments":[{"id":"092612-2026"}]},{"id":"107","amendments":[{"id":"092612-2026"}]},{"id":"108","amendments":[{"id":"092612-2026"}]},{"id":"109","amendments":[{"id":"092612-2026"}]},{"id":"110","amendments":[{"id":"092612-2026"}]},{"id":"111","amendments":[{"id":"092612-2026"}]},{"id":"112","amendments":[{"id":"092612-2026"}]},{"id":"113","amendments":[{"id":"092612-2026"}]},{"id":"114","amendments":[{"id":"092612-2026"}]},{"id":"115","amendments":[{"id":"092612-2026"}]},{"id":"116","amendments":[{"id":"092612-2026"}]},{"id":"117","amendments":[{"id":"092612-2026"}]},{"id":"118","amendments":[{"id":"092612-2026"}]},{"id":"119","amendments":[{"id":"092612-2026"}]},{"id":"120","amendments":[{"id":"092612-2026"}]},{"id":"121","amendments":[{"id":"092612-2026"}]},{"id":"122","amendments":[{"id":"092612-2026"}]},{"id":"123","amendments":[{"id":"092612-2026"}]},{"id":"124","amendments":[{"id":"092612-2026"}]},{"id":"125","amendments":[{"id":"092612-2026"}]},{"id":"126","amendments":[{"id":"092612-2026"}]},{"id":"127","amendments":[{"id":"092612-2026"}]}]

In [61]:
import json

parsed_awards = json.loads(data)

print(json.dumps(parsed_awards, indent=2))

[
  {
    "id": "1",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "2",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "3",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "4",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "5",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "6",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "7",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "8",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "9",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "10",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "11",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "12",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "13",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "14",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "15",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "16",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "17",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "18",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "19",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "20",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "21",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "22",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "23",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "24",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "25",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "26",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "27",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "28",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "29",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "30",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "31",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "32",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "33",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "34",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "35",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "36",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "37",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "38",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "39",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "40",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "41",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "42",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "43",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "44",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "45",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "46",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "47",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "48",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "49",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "50",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "51",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "52",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "53",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "54",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "55",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "56",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "57",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "58",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "59",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "60",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "61",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "62",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "63",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "64",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "65",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "66",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "67",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "68",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "69",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "70",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "71",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "72",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "73",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "74",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "75",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "76",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "77",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "78",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "79",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "80",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "81",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "82",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "83",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "84",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "85",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "86",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "87",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "88",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "89",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "90",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "91",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "92",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "93",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "94",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "95",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "96",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "97",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "98",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "99",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "100",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "101",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "102",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "103",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "104",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "105",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "106",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "107",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "108",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "109",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "110",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "111",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "112",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "113",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "114",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "115",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "116",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "117",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "118",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "119",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "120",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "121",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "122",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "123",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "124",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "125",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "126",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  },
  {
    "id": "127",
    "amendments": [
      {
        "id": "092612-2026"
      }
    ]
  }
]

In [62]:
data = conn.execute("""
    SELECT
        release_id,
        raw_json -> '$.awards' AS awards
    FROM raw_releases
    WHERE json_array_length(raw_json, '$.awards') = 1
    LIMIT 1
""").fetchone()

print(data[0])
print(data[1])

092770-2026
[{"id":"1","status":"active","mainProcurementCategory":"goods","suppliers":[{"id":"GB-PPON-PBHQ-8556-RPBN","name":"Alliance Healthcare"},{"id":"GB-PPON-PLCQ-5553-XNTM","name":"AAH Pharmaceuticals Limited"},{"id":"GB-PPON-PHTH-2722-DWLT","name":"Phoenix Healthcare"},{"id":"GB-PPON-PDHW-3339-CRZN","name":"Mawdsley-Brooks & Co Ltd"}],"items":[{"id":"1","additionalClassifications":[{"scheme":"CPV","id":"33600000","description":"Pharmaceutical products"}],"deliveryAddresses":[{"region":"UKC","country":"GB","countryName":"United Kingdom"},{"region":"UKD","country":"GB","countryName":"United Kingdom"},{"region":"UKE","country":"GB","countryName":"United Kingdom"}],"relatedLot":"1"}],"relatedLots":["1"]}]

In [73]:
data = conn.execute("""
    SELECT
    r.release_id,
    a.value ->> '$.id' as award_id,
    a.value ->> '$.status' as award_status,
    a.value ->> '$.mainProcurementCategory' as procurement_category
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a
WHERE r.release_id = '092770-2026'
""").df()

data

    release_id award_id award_status procurement_category
0  092770-2026        1       active                goods

In [74]:
data = conn.execute("""
    SELECT
    count(*)
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a
""").df()

data

   count_star()
0          1574

In [79]:
data = conn.execute("""
    SELECT
    r.release_id,
    a.value ->> '$.id' as award_id,
    count(*) as total
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a
group by r.release_id,award_id
having total > 1
order by total desc
""").df()

data

Empty DataFrame
Columns: [release_id, award_id, total]
Index: []

In [80]:
data = conn.execute("""
    SELECT
    fields.key
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a,
     json_each(a.value) fields
WHERE r.release_id = '092770-2026'
""").df()

data

                       key
0              relatedLots
1                    items
2                suppliers
3  mainProcurementCategory
4                   status
5                       id

In [81]:
data = conn.execute("""
    SELECT
    fields.key, count(*)
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a,
     json_each(a.value) fields
    group by fields.key
""").df()

data

                                key  count_star()
0                       relatedLots          1388
1                  standstillPeriod            95
2                     statusDetails            18
3                           renewal           150
4                    subcontracting             5
5                 hasSubcontracting             4
6                             title           570
7           mainProcurementCategory           776
8                           options            34
9                        hasRenewal           150
10                        suppliers          1357
11                       amendments           192
12  additionalProcurementCategories             5
13                       hasOptions            34
14                  finalStatusDate            20
15                           status          1388
16      assessmentSummariesDateSent           141
17                               id          1574
18                            value           296
19                        documents           299
20                            items           776
21                   contractPeriod           296
22                             date           240
23                       milestones           296
24                   aboveThreshold           296

In [84]:
data = conn.execute("""
    SELECT
    a.value -> '$.value' AS award_value
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a
    WHERE (a.value -> '$.value') IS NOT NULL
    limit 5
""").df()

data

                                         award_value
0  {"amountGross":379320.0,"amount":316100.0,"cur...
1  {"amountGross":2400000,"amount":2000000,"curre...
2          {"amountGross":384452.0,"currency":"GBP"}
3          {"amountGross":214423.0,"currency":"GBP"}
4  {"amountGross":1945581.6,"amount":1621318.0,"c...

In [88]:
data = conn.execute("""
    SELECT
    COUNT(a.value ->> '$.value.amount') as count_amount,
    COUNT(a.value ->> '$.value.amountGross') as count_gross,
    COUNT(a.value ->> '$.value.currency') as count_currency
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a
    WHERE (a.value -> '$.value') IS NOT NULL
    limit 5
""").df()

data

   count_amount  count_gross  count_currency
0           265          296             296

In [107]:
data = conn.execute("""
    SELECT
    r.release_id,
    r.ocid,
    r.release_date,
    a.value ->> '$.id' AS award_id,
    a.value ->> '$.title' AS award_title,
    a.value ->> '$.status' as award_status,
    a.value ->> '$.mainProcurementCategory' as procurement_category,
    CAST(a.value ->> '$.date' AS TIMESTAMPTZ) AS award_date,
    CAST(a.value ->> '$.value.amount' AS DECIMAL(19,2)) AS award_value,
    CAST(a.value ->> '$.value.amountGross' AS DECIMAL(19,2)) AS award_value_gross,
    a.value ->> '$.value.currency' AS currency
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a
    limit 5
""").df()

data.dtypes

release_id                                     object
ocid                                           object
release_date            datetime64[us, Europe/London]
award_id                                       object
award_title                                    object
award_status                                   object
procurement_category                           object
award_date              datetime64[us, Europe/London]
award_value                                   float64
award_value_gross                             float64
currency                                       object
dtype: object

In [108]:
data = conn.execute("""
    SELECT
    a.value ->> '$.date' AS award_date
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a
WHERE (a.value -> '$.date') IS NOT NULL
LIMIT 10
""").df()

data

                  award_date
0  2026-08-10T00:00:00+01:00
1  2026-09-18T00:00:00+01:00
2  2026-10-01T00:00:00+01:00
3  2026-10-01T00:00:00+01:00
4  2026-08-05T00:00:00+01:00
5  2026-10-01T00:00:00+01:00
6  2026-09-24T00:00:00+01:00
7  2026-09-16T00:00:00+01:00
8  2026-10-01T00:00:00+01:00
9  2026-09-23T00:00:00+01:00

In [117]:
conn.close()

In [112]:
conn = duckdb.connect("procurement.duckdb")

In [118]:
data = conn.execute("""
    SELECT COUNT(*)
FROM stg_awards
""").df()

data

ConnectionException: Connection Error: Connection already closed!

In [119]:
## Supplier exploration
conn = duckdb.connect("procurement.duckdb")

In [136]:
data = conn.execute("""
 SELECT COUNT(*) AS supplier_count
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a,
     json_each(a.value, '$.suppliers') b
     
     """).df()
data

   supplier_count
0            2096

In [139]:
data = conn.execute("""
 SELECT
    fields.key,
    COUNT(*) AS occurrences
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a,
     json_each(a.value, '$.suppliers') b,
     json_each(b.value) fields
GROUP BY fields.key
ORDER BY occurrences DESC
     """).df()
data

    key  occurrences
0  name         2096
1    id         2096

In [141]:
data = conn.execute("""
 SELECT
    b.value ->> '$.id' AS supplier_id,
    COUNT(*) AS occurrences
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a,
     json_each(a.value, '$.suppliers') b,
     
GROUP BY supplier_id
ORDER BY occurrences DESC
     """).df()
data

                 supplier_id  occurrences
0            GB-COH-00123665           11
1     GB-PPON-PZRT-9169-TVMT            9
2              GB-FTS-122307            9
3     GB-PPON-PMHC-9629-CWGZ            8
4     GB-PPON-PJHR-6675-JBPY            8
...                      ...          ...
1555         GB-COH-13448976            1
1556  GB-PPON-PTRZ-2247-YRHT            1
1557         GB-COH-01132885            1
1558         GB-COH-05161508            1
1559         GB-COH-11758568            1

[1560 rows x 2 columns]

In [147]:
data = conn.execute("""
 SELECT
   r.release_id,
a.value ->> '$.id' AS award_id,
b.value ->> '$.id' AS supplier_id,
count(*) as total
FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a,
     json_each(a.value, '$.suppliers') b,
     
GROUP BY r.release_id, award_id, supplier_id
having total > 1
     """).df()
data

Empty DataFrame
Columns: [release_id, award_id, supplier_id, total]
Index: []

In [149]:
data = conn.execute("""
 SELECT
   r.release_id,
a.value ->> '$.id' AS award_id,
b.value ->> '$.id' AS supplier_id,
b.value ->> '$.name' AS supplier_name

FROM raw_releases r,
     json_each(r.raw_json, '$.awards') a,
     json_each(a.value, '$.suppliers') b
     """).df()
data

,release_id,award_id,supplier_id,supplier_name
0,092770-2026,1,GB-PPON-PDHW-3339-CRZN,Mawdsley-Brooks & Co Ltd
1,092768-2026,1,GB-COH-04985828,THAMES21 LIMITED
2,092765-2026,1,GB-COH-07889401,AGILE COLLECTIVE LTD
3,092764-2026,1,GB-COH-14141136,MAZE FIRE CONSULTING LIMITED
4,092762-2026,2,GB-PPON-PMGJ-2542-MDMZ,Political Engagement Ltd
...,...,...,...,...
2091,093037-2026,2,GB-COH-RC000017,ASSOCIATION OF COMMONWEALTH UNIVERSITIES
2092,093037-2026,2,GB-COH-11198794,ALEPH STRATEGIES LIMITED
2093,093037-2026,2,GB-PPON-PZVB-4699-HWWW,Agbo Ahamefuna Consult
2094,093037-2026,2,GB-PPON-PCXD-2676-NRTD,Additional Research
2095,093037-2026,2,GB-COH-05572704,ACER INTERNATIONAL UNITED KINGDOM LIMITED

In [151]:
conn.close()

In [152]:
conn = duckdb.connect("procurement.duckdb")

In [153]:
data = conn.execute("""
    SELECT COUNT(*) AS supplier_count
    FROM stg_award_suppliers
""").df()

data

   supplier_count
0            2096

In [154]:
data = conn.execute("""
    SELECT *
    FROM stg_award_suppliers
    LIMIT 10
""").df()

data

,release_id,award_id,supplier_id,supplier_name
0,092770-2026,1,GB-PPON-PDHW-3339-CRZN,Mawdsley-Brooks & Co Ltd
1,092768-2026,1,GB-COH-04985828,THAMES21 LIMITED
2,092765-2026,1,GB-COH-07889401,AGILE COLLECTIVE LTD
3,092764-2026,1,GB-COH-14141136,MAZE FIRE CONSULTING LIMITED
4,092762-2026,2,GB-PPON-PMGJ-2542-MDMZ,Political Engagement Ltd
5,092757-2026,1,GB-PPON-PNYQ-4199-GPZX,Oil 4 Wales Ltd
6,092756-2026,1,GB-COH-04160275,ECOONLINE UK LIMITED
7,092755-2026,092755-2026-1,GB-FTS-187216,Norfolk and Suffolk NHS Foundation Trust
8,092754-2026,092754-2026-1,GB-FTS-187215,Hertfordshire Partnership University NHS Found...
9,092753-2026,092753-2026-GMCA 1793-1,GB-COH-01628868,Civica UK Limited

In [155]:
data = conn.execute("""
    SELECT  release_id,
            award_id,
            supplier_id,
            count(*)
    FROM stg_award_suppliers
    group by release_id,
            award_id,
            supplier_id
    HAVING count(*) > 1
""").df()

data

Empty DataFrame
Columns: [release_id, award_id, supplier_id, count_star()]
Index: []

In [157]:
conn.close()

In [158]:
conn = duckdb.connect("procurement.duckdb")

In [164]:
data = conn.execute("""
with ranked_releases as(
    SELECT  ocid, release_id, release_date,
    ROW_NUMBER() OVER (
    PARTITION BY ocid
    ORDER BY release_date DESC
) AS release_rank
    FROM stg_releases)
    
    select * from ranked_releases
    where release_rank = 1
""").df()

data

                    ocid   release_id              release_date  release_rank
0     ocds-h6vhtk-06759b  092770-2026 2026-10-01 11:46:44+01:00             1
1     ocds-h6vhtk-077e7b  092769-2026 2026-10-01 11:46:41+01:00             1
2     ocds-h6vhtk-077e7a  092768-2026 2026-10-01 11:46:10+01:00             1
3     ocds-h6vhtk-06ecf6  092767-2026 2026-10-01 11:45:29+01:00             1
4     ocds-h6vhtk-064e67  092766-2026 2026-10-01 11:44:37+01:00             1
...                  ...          ...                       ...           ...
1087  ocds-h6vhtk-077f22  093074-2026 2026-10-02 07:47:47+01:00             1
1088  ocds-h6vhtk-06d28d  093580-2026 2026-10-04 14:29:57+01:00             1
1089  ocds-h6vhtk-07803a  093579-2026 2026-10-04 14:05:53+01:00             1
1090  ocds-h6vhtk-07803b  093582-2026 2026-10-04 18:52:05+01:00             1
1091  ocds-h6vhtk-077b07  093581-2026 2026-10-04 17:02:56+01:00             1

[1092 rows x 4 columns]

In [166]:
print("Rows:", len(data))
print("Distinct OCIDs:", data["ocid"].nunique())
data[data["ocid"].duplicated(keep=False)]

Rows: 1092
Distinct OCIDs: 1092

Empty DataFrame
Columns: [ocid, release_id, release_date, release_rank]
Index: []

In [168]:
data = conn.execute("""

    SELECT  ocid, release_date, count(*)
    FROM stg_releases
    group by ocid, release_date
    having count(*) > 1
    
""").df()

data

Empty DataFrame
Columns: [ocid, release_date, count_star()]
Index: []

In [172]:
data = conn.execute("""
    with ranked_releases as(
    SELECT  
    ocid,
    release_id,
    release_date,
    buyer_name,
    tender_title,
    tender_status,
    procurement_method,
    tender_value,
    currency,
    ROW_NUMBER() OVER (
    PARTITION BY ocid
    ORDER BY release_date DESC
    ) AS release_rank
    FROM stg_releases)

    select ocid,
    release_id,
    release_date,
    buyer_name,
    tender_title,
    tender_status,
    procurement_method,
    tender_value,
    currency from ranked_releases where release_rank = 1
""").df()

data

,ocid,release_id,release_date,buyer_name,tender_title,tender_status,procurement_method,tender_value,currency,release_rank
0,ocds-h6vhtk-077e7b,092769-2026,2026-10-01 11:46:41+01:00,Post Office Limited,Post Office Branch - Inchture,active,open,NaN,GBP,1
1,ocds-h6vhtk-077e7a,092768-2026,2026-10-01 11:46:10+01:00,London Borough of Bromley,"Water Quality Monitoring, Citizen Science & Co...",complete,limited,NaN,None,1
2,ocds-h6vhtk-069509,092763-2026,2026-10-01 11:43:07+01:00,"Department for Science, Innovation & Technology",UKSAC26_0043 EO Data Hub Service Delivery,planning,None,5000000.0,GBP,1
3,ocds-h6vhtk-077e76,092760-2026,2026-10-01 11:37:15+01:00,Cheshire East Council,Payment services provider and merchant acquire...,active,open,400000.0,GBP,1
4,ocds-h6vhtk-077e73,092756-2026,2026-10-01 11:31:47+01:00,UK Research and Innovation,COSHH Risk as a Service,complete,direct,NaN,None,1
...,...,...,...,...,...,...,...,...,...,...
1087,ocds-h6vhtk-077f36,093108-2026,2026-10-02 09:09:13+01:00,COLLEGE OF POLICING LIMITED,Google Gemini Expansion and Tool Theft,complete,direct,NaN,None,1
1088,ocds-h6vhtk-077f31,093099-2026,2026-10-02 08:56:11+01:00,The Highland Council,Corran Ferry New Electric Vessel (CFNEV),active,open,NaN,None,1
1089,ocds-h6vhtk-077f25,093081-2026,2026-10-02 08:16:10+01:00,Neath Port Talbot County Borough Council,LPC1: Peatland Restoration and Grazing Infrast...,active,open,174078.0,GBP,1
1090,ocds-h6vhtk-067bb5,093076-2026,2026-10-02 07:57:04+01:00,COUNTY DURHAM AND DARLINGTON NHS FOUNDATION TRUST,Provision of Lease Car Management Services,active,open,386280.0,GBP,1
1091,ocds-h6vhtk-077b07,093581-2026,2026-10-04 17:02:56+01:00,Ingoldmells Parish Council,Play Ground Refurbishment x 2,active,open,120000.0,GBP,1

In [174]:
conn.close()

In [175]:
conn = duckdb.connect("procurement.duckdb")

In [176]:
data = conn.execute("""
    SELECT
        COUNT(*) AS rows,
        COUNT(DISTINCT ocid) AS distinct_ocids
    FROM current_procurements
""").df()

data

   rows  distinct_ocids
0  1092            1092

In [177]:
data = conn.execute("""
    SELECT *
    FROM current_procurements
    LIMIT 10
""").df()

data

,ocid,release_id,release_date,buyer_name,tender_title,tender_status,procurement_method,tender_value,currency
0,ocds-h6vhtk-077e7b,092769-2026,2026-10-01 11:46:41+01:00,Post Office Limited,Post Office Branch - Inchture,active,open,NaN,GBP
1,ocds-h6vhtk-077e7a,092768-2026,2026-10-01 11:46:10+01:00,London Borough of Bromley,"Water Quality Monitoring, Citizen Science & Co...",complete,limited,NaN,None
2,ocds-h6vhtk-069509,092763-2026,2026-10-01 11:43:07+01:00,"Department for Science, Innovation & Technology",UKSAC26_0043 EO Data Hub Service Delivery,planning,None,5000000.0,GBP
3,ocds-h6vhtk-077e76,092760-2026,2026-10-01 11:37:15+01:00,Cheshire East Council,Payment services provider and merchant acquire...,active,open,400000.0,GBP
4,ocds-h6vhtk-077e73,092756-2026,2026-10-01 11:31:47+01:00,UK Research and Innovation,COSHH Risk as a Service,complete,direct,NaN,None
5,ocds-h6vhtk-077e6b,092741-2026,2026-10-01 11:18:36+01:00,The Christie NHS Foundation Trust,PIC iX HardwarePatient Information Center iX E...,complete,direct,NaN,None
6,ocds-h6vhtk-077e63,092731-2026,2026-10-01 11:09:05+01:00,Norfolk and Norwich University Hospitals NHS F...,Norfolk and Norwich University Hospitals NHS F...,complete,limited,NaN,None
7,ocds-h6vhtk-077dcf,092716-2026,2026-10-01 10:49:39+01:00,ARCHES HOUSING LIMITED,Arches HA TCI 2026,complete,selective,NaN,None
8,ocds-h6vhtk-077e53,092708-2026,2026-10-01 10:41:38+01:00,Department for Business & Trade,DBT and The British Film Commission 2026,complete,direct,NaN,None
9,ocds-h6vhtk-067c3b,092704-2026,2026-10-01 10:39:17+01:00,NATIONAL GRID UK LIMITED,"Civil Works within NGED Substations 132kV, 66k...",complete,selective,NaN,None

In [178]:
conn.close()

In [179]:
conn = duckdb.connect("procurement.duckdb")

In [185]:
data = conn.execute("""
    SELECT 
            r.ocid,
            r.release_id,
            r.release_date,
            award_id,
            award_status,
            award_value,
            award_value_gross,
            r.currency
    FROM stg_releases r
    LEFT JOIN stg_awards a
    ON r.release_id = a.release_id
    WHERE r.ocid = 'ocds-h6vhtk-029897'
    ORDER BY r.release_date, a.award_id
""").df()

data

,ocid,release_id,release_date,award_id,award_status,award_value,award_value_gross,currency
0,ocds-h6vhtk-029897,092702-2026,2026-10-01 10:37:42+01:00,092702-2026-1,active,NaN,NaN,None
1,ocds-h6vhtk-029897,093155-2026,2026-10-02 10:03:43+01:00,093155-2026-1,active,NaN,NaN,None
2,ocds-h6vhtk-029897,093156-2026,2026-10-02 10:05:43+01:00,093156-2026-1,active,NaN,NaN,None
3,ocds-h6vhtk-029897,093159-2026,2026-10-02 10:07:43+01:00,093159-2026-1,active,NaN,NaN,None
4,ocds-h6vhtk-029897,093215-2026,2026-10-02 11:13:39+01:00,093215-2026-1,active,NaN,NaN,None
5,ocds-h6vhtk-029897,093251-2026,2026-10-02 11:41:45+01:00,093251-2026-1,active,NaN,NaN,None

In [187]:
data = conn.execute("""
    SELECT 
            count(*), count(*) FILTER (award_id LIKE release_id || '%')
    FROM stg_awards r
""").df()

data

   count_star()  count_star() FILTER (WHERE (award_id ~~ (release_id || '%')))
0          1574                                                583

In [188]:
data = conn.execute("""
    SELECT
    release_id,
    award_id
FROM stg_awards
WHERE award_id NOT LIKE release_id || '%'
LIMIT 20
""").df()

data

     release_id award_id
0   092770-2026        1
1   092768-2026        1
2   092765-2026        1
3   092764-2026        1
4   092762-2026        2
5   092757-2026        1
6   092756-2026        1
7   092747-2026        1
8   092746-2026        1
9   092744-2026        1
10  092743-2026        1
11  092742-2026        1
12  092741-2026        1
13  092739-2026        1
14  092738-2026        1
15  092737-2026        1
16  092736-2026        1
17  092735-2026        1
18  092734-2026        1
19  092733-2026        1

In [197]:
data = conn.execute("""
    SELECT 
            r.ocid,
            award_id,
            COUNT(DISTINCT r.release_id) as number_of_releases
    FROM stg_releases r
    LEFT JOIN stg_awards a
    ON r.release_id = a.release_id
    WHERE a.award_id IS NOT NULL
    group by r.ocid, award_id
    HAVING COUNT(DISTINCT r.release_id) > 1
    order by number_of_releases desc
""").df()

data

                  ocid award_id  number_of_releases
0   ocds-h6vhtk-06f8a4        1                   3
1   ocds-h6vhtk-0510f8       88                   2
2   ocds-h6vhtk-0510f8       66                   2
3   ocds-h6vhtk-0510f8       21                   2
4   ocds-h6vhtk-0510f8       46                   2
..                 ...      ...                 ...
79  ocds-h6vhtk-077da5        1                   2
80  ocds-h6vhtk-0510f8      126                   2
81  ocds-h6vhtk-077f9b        1                   2
82  ocds-h6vhtk-0510f8       45                   2
83  ocds-h6vhtk-077e25        1                   2

[84 rows x 3 columns]

In [211]:
data = conn.execute("""
    WITH award_counts AS (
    SELECT 
            r.ocid,
            r.release_id,
            r.release_date,
            COUNT(a.award_id) AS award_count
    FROM stg_releases r
    LEFT JOIN stg_awards a
    ON r.release_id = a.release_id
    group by r.ocid, r.release_id, r.release_date,
    ),

    award_changes AS (
        SELECT *,
               LAG(award_count) OVER (
                   PARTITION BY ocid
                   ORDER BY release_date
               ) AS previous_award_count
        FROM award_counts
    )
    
    SELECT *
    FROM award_changes
    where award_count != previous_award_count
    
""").df()

data

,ocid,release_id,release_date,award_count,previous_award_count
0,ocds-h6vhtk-0605c1,093225-2026,2026-10-02 11:23:32+01:00,1,0
1,ocds-h6vhtk-059971,092904-2026,2026-10-01 14:38:46+01:00,1,2
2,ocds-h6vhtk-0510f8,093576-2026,2026-10-02 23:30:45+01:00,53,127

In [212]:
data = conn.execute("""
    SELECT
        r.release_id,
        r.release_date,
        a.award_id,
        a.award_status
    FROM stg_releases r
    LEFT JOIN stg_awards a
        ON r.release_id = a.release_id
    WHERE r.ocid = 'ocds-h6vhtk-059971'
    ORDER BY r.release_date, a.award_id
""").df()

data

    release_id              release_date award_id award_status
0  092875-2026 2026-10-01 13:58:18+01:00        1      pending
1  092875-2026 2026-10-01 13:58:18+01:00        2      pending
2  092904-2026 2026-10-01 14:38:46+01:00        2      pending

In [216]:
data = conn.execute("""
    SELECT
    p.ocid,
    p.release_id,
    p.release_date,
    p.buyer_name,
    p.tender_title,
    
    a.award_id,
    a.award_title,
    a.award_status,
    a.award_date,
    a.award_value,
    a.award_value_gross,
    a.currency
FROM current_procurements p
JOIN stg_awards a
    ON p.release_id = a.release_id
    WHERE p.ocid = 'ocds-h6vhtk-059971'
""").df()

data

,ocid,release_id,release_date,buyer_name,tender_title,award_id,award_title,award_status,award_date,award_value,award_value_gross,currency
0,ocds-h6vhtk-059971,092904-2026,2026-10-01 14:38:46+01:00,New College Durham,Digital and Media Advertising,2,Lot 2 - Media Advertising,pending,2026-10-01 00:00:00+01:00,258000.0,258000.0,GBP

In [219]:
conn.close()

In [220]:
conn = duckdb.connect("procurement.duckdb")

In [221]:
data = conn.execute("""
    SELECT ocid, award_id, count(*)
    FROM current_awards p
    group by ocid, award_id
    having count(*) > 1
""").df()

data

Empty DataFrame
Columns: [ocid, award_id, count_star()]
Index: []

In [224]:
conn.close()

In [2]:
conn = duckdb.connect("procurement.duckdb")

NameError: name 'duckdb' is not defined

In [5]:
data = conn.execute("""
    select * 
    FROM current_awards a
    limit 2
""").df()

data

,ocid,release_id,release_date,buyer_name,tender_title,award_id,award_title,award_status,award_date,award_value,award_value_gross,currency
0,ocds-h6vhtk-06759b,092770-2026,2026-10-01 11:46:44+01:00,Leeds Teaching Hospitals NHS Trust,NEYPPC Licensed Medicines Provision of Pharmac...,1,None,active,NaT,NaN,NaN,None
1,ocds-h6vhtk-077e7a,092768-2026,2026-10-01 11:46:10+01:00,London Borough of Bromley,"Water Quality Monitoring, Citizen Science & Co...",1,None,active,NaT,NaN,NaN,None

In [6]:
data = conn.execute("""
    select * 
    FROM stg_award_suppliers  a
    limit 2
""").df()

data

    release_id award_id             supplier_id             supplier_name
0  092770-2026        1  GB-PPON-PDHW-3339-CRZN  Mawdsley-Brooks & Co Ltd
1  092768-2026        1         GB-COH-04985828          THAMES21 LIMITED

In [12]:
data = conn.execute("""
    select 
        a.ocid,
        a.release_id,
        a.award_id,
        a.award_value,
        count(*) as supplier_count
    FROM current_awards a
    JOIN stg_award_suppliers s
    ON a.release_id = s.release_id
    AND a.award_id = s.award_id
    group by ocid,
        a.release_id,
        a.award_id,
        a.award_value,
        having count(*) > 1
""").df()

data

                   ocid   release_id award_id  award_value  supplier_count
0    ocds-h6vhtk-0676f9  092591-2026        5          NaN               3
1    ocds-h6vhtk-068a27  092406-2026        1          NaN               3
2    ocds-h6vhtk-06b3ca  092891-2026        1     999999.0               2
3    ocds-h6vhtk-06afdb  093497-2026        1          NaN               2
4    ocds-h6vhtk-058e6b  093428-2026        1          NaN              12
..                  ...          ...      ...          ...             ...
103  ocds-h6vhtk-066891  093427-2026        6    2000000.0               4
104  ocds-h6vhtk-06cc1f  092844-2026        1          NaN               5
105  ocds-h6vhtk-051d65  092611-2026        1   39000000.0               2
106  ocds-h6vhtk-050a69  093562-2026        5          NaN               2
107  ocds-h6vhtk-06893b  092603-2026        5     300000.0               3

[108 rows x 5 columns]

In [13]:
data = conn.execute("""
    select *
    from stg_award_suppliers
    where release_id = '092891-2026'
        
""").df()

data

    release_id award_id      supplier_id                supplier_name
0  092891-2026        1  GB-COH-04082871  FG LIBRARY PRODUCTS LIMITED
1  092891-2026        1  GB-COH-06482850     THEDESIGNCONCEPT LIMITED

In [16]:
data = conn.execute("""
    select supplier_id, COUNT(DISTINCT supplier_name)
    from stg_award_suppliers
    group by supplier_id
    having COUNT(DISTINCT supplier_name) > 1
""").df()

data

               supplier_id  count(DISTINCT supplier_name)
0                 GB-COH-0                              5
1          GB-COH-05381795                              2
2          GB-COH-IP29827R                              3
3          GB-COH-00337663                              2
4          GB-COH-05302511                              2
5   GB-PPON-PZRT-9169-TVMT                              2
6   GB-PPON-PPQG-1767-NGCR                              2
7          GB-COH-10382721                              2
8          GB-COH-12214029                              2
9          GB-COH-00446897                              2
10         GB-COH-01628868                              2
11         GB-COH-03717583                              2
12         GB-COH-06655187                              2
13         GB-COH-10878116                              2
14         GB-COH-03376202                              2
15         GB-COH-05367714                              2
16         GB-COH-01457814                              2
17  GB-PPON-PBVD-1549-BYRH                              2
18         GB-COH-04284822                              2

In [21]:
data = conn.execute("""
    select *
    from stg_award_suppliers
    WHERE supplier_id IN (
    SELECT supplier_id
    FROM stg_award_suppliers
    GROUP BY supplier_id
    HAVING COUNT(DISTINCT upper(supplier_name)) > 1
) and supplier_id != 'GB-COH-0'
order by supplier_id, supplier_name
""").df()

data

,release_id,award_id,supplier_id,supplier_name
0,092603-2026,13,GB-COH-03376202,OPENVIEW SECURITY SOLUTIONS LIMITED
1,092603-2026,12,GB-COH-03376202,OPENVIEW SECURITY SOLUTIONS LIMITED
2,092437-2026,1,GB-COH-03376202,OpenView Security
3,092985-2026,1,GB-COH-03717583,Synertec Limited
4,092523-2026,1,GB-COH-03717583,Synertec Ltd
5,092674-2026,1,GB-COH-04284822,Affinity Workforce Solutions Ltd T/A Career Te...
6,092688-2026,1,GB-COH-04284822,Affinity Workforce Solutions T/A Career Teache...
7,092668-2026,1,GB-COH-10878116,CIPD HR Inform
8,092667-2026,1,GB-COH-10878116,CRONER-I LIMITED
9,092387-2026,092387-2026-1,GB-COH-IP29827R,East Berkshire Primary Care
10,092388-2026,092388-2026-1,GB-COH-IP29827R,East Berkshire Primary Care Limited
11,092393-2026,092393-2026-1,GB-COH-IP29827R,East Berkshire Primary Care Out of Hours Servi...

In [22]:
data = conn.execute("""
    SELECT
    supplier_id,
    COUNT(*) AS occurrences,
    COUNT(DISTINCT UPPER(TRIM(supplier_name))) AS distinct_names
FROM stg_award_suppliers
GROUP BY supplier_id
ORDER BY distinct_names DESC, occurrences DESC
""").df()

data

                 supplier_id  occurrences  distinct_names
0                   GB-COH-0            5               5
1            GB-COH-IP29827R            3               3
2            GB-COH-03376202            3               2
3            GB-COH-10878116            2               2
4            GB-COH-03717583            2               2
...                      ...          ...             ...
1555         GB-COH-07704832            1               1
1556         GB-COH-05096438            1               1
1557         GB-COH-05014538            1               1
1558         GB-COH-RC000017            1               1
1559  GB-PPON-PPXZ-1454-GZLL            1               1

[1560 rows x 3 columns]

In [41]:
data = conn.execute("""
    WITH ranked_suppliers AS (
    SELECT
        s.supplier_id,
        s.supplier_name,
        s.release_id,
        r.release_date,
        CASE
            WHEN s.supplier_id = 'GB-COH-0'
                THEN UPPER(TRIM(s.supplier_name))
            ELSE s.supplier_id
        END AS supplier_key,
        ROW_NUMBER() OVER (
            PARTITION BY s.supplier_id
            ORDER BY r.release_date DESC
        ) AS supplier_rank
    FROM stg_award_suppliers s
    JOIN stg_releases r
        ON s.release_id = r.release_id
    
)

SELECT *
FROM ranked_suppliers
WHERE supplier_id = 'GB-COH-0'
""").df()

data

,supplier_id,supplier_name,release_id,release_date,supplier_key,supplier_rank
0,GB-COH-0,Dee Banks School,092552-2026,2026-09-30 16:21:07+01:00,DEE BANKS SCHOOL,1
1,GB-COH-0,Care4CE,092552-2026,2026-09-30 16:21:07+01:00,CARE4CE,2
2,GB-COH-0,Springwood Heath Primary School (CMS) - 11085 ...,092552-2026,2026-09-30 16:21:07+01:00,SPRINGWOOD HEATH PRIMARY SCHOOL (CMS) - 11085 ...,3
3,GB-COH-0,Mr Naveed Hussain & Mr Mohammad Hussain & Mrs ...,092552-2026,2026-09-30 16:21:07+01:00,MR NAVEED HUSSAIN & MR MOHAMMAD HUSSAIN & MRS ...,4
4,GB-COH-0,Lancashire County Council,092552-2026,2026-09-30 16:21:07+01:00,LANCASHIRE COUNTY COUNCIL,5

In [47]:
data = conn.execute("""
    WITH supplier_keys AS (
    SELECT
        s.supplier_id,
        s.supplier_name,
        s.release_id,
        r.release_date,
        CASE
            WHEN s.supplier_id = 'GB-COH-0'
                THEN UPPER(TRIM(s.supplier_name))
            ELSE s.supplier_id
        END AS supplier_key
    FROM stg_award_suppliers s
    JOIN stg_releases r
        ON s.release_id = r.release_id   
),
ranked_suppliers AS (
    SELECT
        *,
        ROW_NUMBER() OVER (
            PARTITION BY supplier_key
            ORDER BY release_date DESC
        ) AS supplier_rank
    FROM supplier_keys
)

SELECT *
FROM ranked_suppliers
WHERE supplier_rank = 1
""").df()

data

,supplier_id,supplier_name,release_id,release_date,supplier_key,supplier_rank
0,GB-COH-04160275,ECOONLINE UK LIMITED,092756-2026,2026-10-01 11:31:47+01:00,GB-COH-04160275,1
1,GB-FTS-187216,Norfolk and Suffolk NHS Foundation Trust,092755-2026,2026-10-01 11:29:12+01:00,GB-FTS-187216,1
2,GB-PPON-PPQG-1767-NGCR,British Gas Trading Limited,093362-2026,2026-10-02 13:39:39+01:00,GB-PPON-PPQG-1767-NGCR,1
3,GB-COH-OC310651,Daniel Connal Partnership,092727-2026,2026-10-01 11:06:41+01:00,GB-COH-OC310651,1
4,GB-PPON-PQHC-6774-DXHX,British Film Commission,092708-2026,2026-10-01 10:41:38+01:00,GB-PPON-PQHC-6774-DXHX,1
...,...,...,...,...,...,...
1559,GB-COH-14598032,FRY CREATIVE CONSULTING LIMITED,093037-2026,2026-10-01 16:57:18+01:00,GB-COH-14598032,1
1560,GB-CHC-1100990,CoLab Exeter,093449-2026,2026-10-02 15:10:19+01:00,GB-CHC-1100990,1
1561,GB-COH-07559200,BACK TO WORK TRAINING LIMITED,093449-2026,2026-10-02 15:10:19+01:00,GB-COH-07559200,1
1562,GB-PPON-PHZN-7222-VGRV,Stephen Hignell,093037-2026,2026-10-01 16:57:18+01:00,GB-PPON-PHZN-7222-VGRV,1
1563,GB-PPON-PZVB-4699-HWWW,Agbo Ahamefuna Consult,093037-2026,2026-10-01 16:57:18+01:00,GB-PPON-PZVB-4699-HWWW,1

In [48]:
conn.close()

In [49]:
conn = duckdb.connect("procurement.duckdb")

In [51]:
data = conn.execute("""
SELECT *
FROM dim_suppliers
where supplier_id = 'GB-COH-0'
limit 10
""").df()

data

,supplier_key,supplier_id,supplier_name,release_id,release_date
0,DEE BANKS SCHOOL,GB-COH-0,Dee Banks School,092552-2026,2026-09-30 16:21:07+01:00
1,LANCASHIRE COUNTY COUNCIL,GB-COH-0,Lancashire County Council,092552-2026,2026-09-30 16:21:07+01:00
2,MR NAVEED HUSSAIN & MR MOHAMMAD HUSSAIN & MRS ...,GB-COH-0,Mr Naveed Hussain & Mr Mohammad Hussain & Mrs ...,092552-2026,2026-09-30 16:21:07+01:00
3,SPRINGWOOD HEATH PRIMARY SCHOOL (CMS) - 11085 ...,GB-COH-0,Springwood Heath Primary School (CMS) - 11085 ...,092552-2026,2026-09-30 16:21:07+01:00
4,CARE4CE,GB-COH-0,Care4CE,092552-2026,2026-09-30 16:21:07+01:00

In [52]:
data = conn.execute("""
SELECT
    a.ocid,
    a.release_id,
    a.award_id,
    CASE
    WHEN s.supplier_id = 'GB-COH-0'
        THEN UPPER(TRIM(s.supplier_name))
    ELSE s.supplier_id
    END AS supplier_key
FROM current_awards a
JOIN stg_award_suppliers s
    on a.release_id = s.release_id
    and a.award_id = s.award_id
""").df()

data

                    ocid   release_id award_id            supplier_key
0     ocds-h6vhtk-06759b  092770-2026        1  GB-PPON-PDHW-3339-CRZN
1     ocds-h6vhtk-077e7a  092768-2026        1         GB-COH-04985828
2     ocds-h6vhtk-077e79  092765-2026        1         GB-COH-07889401
3     ocds-h6vhtk-06db97  092762-2026        2  GB-PPON-PMGJ-2542-MDMZ
4     ocds-h6vhtk-06d83e  092757-2026        1  GB-PPON-PNYQ-4199-GPZX
...                  ...          ...      ...                     ...
2049  ocds-h6vhtk-06798b  093037-2026        2         GB-COH-RC000017
2050  ocds-h6vhtk-06798b  093037-2026        2         GB-COH-11198794
2051  ocds-h6vhtk-06798b  093037-2026        2  GB-PPON-PZVB-4699-HWWW
2052  ocds-h6vhtk-06798b  093037-2026        2  GB-PPON-PCXD-2676-NRTD
2053  ocds-h6vhtk-06798b  093037-2026        2         GB-COH-05572704

[2054 rows x 4 columns]

In [55]:
data = conn.execute("""
SELECT
    a.ocid,
    a.award_id,
    CASE
    WHEN s.supplier_id = 'GB-COH-0'
        THEN UPPER(TRIM(s.supplier_name))
    ELSE s.supplier_id
    END AS supplier_key,
    count(*) as total
FROM current_awards a
JOIN stg_award_suppliers s
    on a.release_id = s.release_id
    and a.award_id = s.award_id
GROUP BY a.ocid, a.award_id, supplier_key
having total > 1
""").df()

data

Empty DataFrame
Columns: [ocid, award_id, supplier_key, total]
Index: []

In [56]:
conn.close()